easy_admin:
    entities:
        Flight:
            class: App\Entity\Flight
            controller: App\Controller\Admin\FlightCrudController
            list:
                fields:
                    - { property: 'flightNumber' }
                    - { property: 'airline' }
                    - { property: 'origin' }
                    - { property: 'destination' }
                    - { property: 'departureTime' }
                    - { property: 'arrivalTime' }
                    - { property: 'price' }
                    - { property: 'availableSeats' }
                    - { property: 'status' }
